model_name: "p-prodec2-modular-variable-pytorch"
model_type: "np-nd-np"
version: "4.0g"
repetition_num: 1
train_epoch_size: 40000
epoch_num: 500
label_dim: 1
edge_feature_dim: 1
meta_feature_dim: 0 # 1
error_dim: 3
metric_index: 0
prediction_dim: 1
hidden_dim: 110  # 110
mem_hidden_dim: 150 #100 150
agg_hidden_dim: 64  # 135 100
mem_agg_hidden_dim: 32  # 50
classifier_dim: 100  # 100 50
batch_size: 5000
# learning_rate: 0.0001
learning_rate: 0.001
exploration: 0.1
verbose: true
randomized: true
train_inner_recurrence_num: 1
train_outer_recurrence_num: 5
test_recurrence_num: 200
max_cache_size: 100000
dropout: 0.2  #0.2
clip_norm: 0.65
#clip_norm: 0.7
#weight_decay: 0.0000000001
weight_decay: 0.000000001
loss_sharpness: 5
train_batch_limit: 5800000
# train_batch_limit: 20000000
test_batch_limit: 5800000
#--------------IF USE GENERATOR--------------
#generator: "v-modular"
#min_n: 5
#max_n: 100
#min_alpha: 5
#max_alpha: 10
#min_k: 2
#max_k: 10
#min_q: 0.8
#max_q: 0.9
#min_c: 10
#max_c: 20
#----------------------------
local_search_iteration: 0
epsilon: 0.5
lambda: 1
batch_replication: 3
# python build/scripts-3.6/satyr-train-test.py config/Train/p-prodec2-modular-variable-pytorch.yaml 